// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/api"
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/api/handler"
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/config"
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/database"
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/repositories"
	"github.com/abhinandpn/MicroServices-GoLang/admin-services/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	db, err := database.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := repositories.NewAdminRepository(db)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	serverHTTP := http.NewServerHTTP(adminHandler)
	return serverHTTP, nil
}
