// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/api"
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/api/handler"
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/config"
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/database"
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/repositories"
	"github.com/abhinandpn/MicroServices-GoLang/product-services/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	db, err := database.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	productRepositorie := repositories.NewProductRepository(db)
	productUseCase := usecase.NewProductUsecase(productRepositorie)
	productHandler := handler.NewProductHandler(productUseCase)
	serverHTTP := http.NewServerHTTP(productHandler)
	return serverHTTP, nil
}
